<?php

namespace AppBundle\Repository;


/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends \Doctrine\ORM\EntityRepository
{

    public function deletedExpiratedTokens()
    {

            $results = $this->getEntityManager()->createQueryBuilder()
                ->delete(UserToken::class, 'usertoken')
                ->where('usertoken.expirationDate < NOW()')
                ->getQuery()
                ->execute()
            ;
    }
}
